### ISSUE TITLE
[Build Error] WebpackError: TypeError: Cannot read property 'isReactComponent' of undefined

### ISSUE THREAD

**Issue by kimnagui** [kimnagui/gatsby-starter-nagui#1]
## Error

![스크린샷 2019-10-28 오후 7 12 06](https://user-images.githubusercontent.com/48215197/67670262-da19d180-f9b6-11e9-9714-edf6a5301453.png)

## Solution

[clickPopup] component change functional component to class component.

```js
// src/components/atoms/clickPopup.js
import React, { Component } from "react";
import styled from "styled-components";
import onClickOutside from "react-onclickoutside";

const Container = styled.div`
    visibility: ${props => (props.show ? "visiable" : "hidden")};
    position: absolute;
    z-index: 1;

    &:after {
        content: "";
        position: absolute;
    }
`;

class ClickPopup extends Component {
    handleClickOutside = e => this.props.close();
    render() {
        const { open, children } = this.props;
        return <Container show={open}>{children}</Container>;
    }
}

export default onClickOutside(ClickPopup);
```

**Comment by BinSquare** [comment]
Hey @kimnagui , I tested and implemented the class component change. Hope you can pull it into the main branch so future users don't run into the same error!

**Comment by kimnagui** [comment]
> Hey @kimnagui , I tested and implemented the class component change. Hope you can pull it into the main branch so future users don't run into the same error!

Thank you !
